import { Box, createTheme, CssBaseline, ThemeProvider } from '@mui/material';
import './global.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import theme from './styles/theme';
import ToastProvider from '../components/ToastrProvider';
export const metadata = {
  title: 'Welcome to weather-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const materialTheme = createTheme({ palette: { mode: 'dark' } });
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <body>
            <ToastProvider>{children}</ToastProvider>
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
